"""empty message

Revision ID: 17be0b7de0f2
Revises: 5cfcda404c4
Create Date: 2015-10-22 18:54:36.727000

"""

# revision identifiers, used by Alembic.
revision = '17be0b7de0f2'
down_revision = '5cfcda404c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankslots',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('itemID', sa.Integer(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['itemID'], ['items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankslots')
    ### end Alembic commands ###
