"""add priceData

Revision ID: 331efa195b55
Revises: 17be0b7de0f2
Create Date: 2015-11-05 03:28:23.948000

"""

# revision identifiers, used by Alembic.
revision = '331efa195b55'
down_revision = '17be0b7de0f2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricedata',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('buyQuantity', sa.Integer(), nullable=True),
                    sa.Column('buyPrice', sa.Integer(), nullable=True),
                    sa.Column('sellQuantity', sa.Integer(), nullable=True),
                    sa.Column('sellPrice', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricedata')
    ### end Alembic commands ###
