"""empty message

Revision ID: 364ed39a52b7
Revises: 37ca4eaa2a0
Create Date: 2015-11-07 13:59:55.405000

"""

# revision identifiers, used by Alembic.
revision = '364ed39a52b7'
down_revision = '37ca4eaa2a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemgametypes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('itemId', sa.Integer(), nullable=True),
                    sa.Column('game_type', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('itemrestrictions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('itemId', sa.Integer(), nullable=True),
                    sa.Column('restriction', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemrestrictions')
    op.drop_table('itemgametypes')
    ### end Alembic commands ###
