"""empty message

Revision ID: 37ca4eaa2a0
Revises: 331efa195b55
Create Date: 2015-11-07 12:59:34.082000

"""

# revision identifiers, used by Alembic.
revision = '37ca4eaa2a0'
down_revision = '331efa195b55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemflags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('itemId', sa.Integer(), nullable=True),
                    sa.Column('flag', sa.Text(), nullable=True),
                    sa.ForeignKeyConstraint(['itemId'], ['items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemflags')
    ### end Alembic commands ###
