"""empty message

Revision ID: 48ef2c8f0c45
Revises: 5a477db4dfff
Create Date: 2015-11-07 18:22:21.317000

"""

# revision identifiers, used by Alembic.
revision = '48ef2c8f0c45'
down_revision = '5a477db4dfff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TPtransactions_broken',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('purchased', sa.DateTime(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TPtransactions_broken')
    ### end Alembic commands ###
