"""empty message

Revision ID: 4f15bfbb7a0a
Revises: 30f140742043
Create Date: 2015-11-08 02:33:24.607000

"""

# revision identifiers, used by Alembic.
revision = '4f15bfbb7a0a'
down_revision = '30f140742043'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maps',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('min_level', sa.Integer(), nullable=True),
                    sa.Column('max_level', sa.Integer(), nullable=True),
                    sa.Column('region_id', sa.Integer(), nullable=True),
                    sa.Column('region_name', sa.Text(), nullable=True),
                    sa.Column('continent_id', sa.Integer(), nullable=True),
                    sa.Column('continent_name', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('pvpmatches',
                    sa.Column('id', sa.String(50), nullable=False),
                    sa.Column('map_id', sa.Integer(), nullable=True),
                    sa.Column('started', sa.DateTime(), nullable=True),
                    sa.Column('ended', sa.DateTime(), nullable=True),
                    sa.Column('result', sa.Text(), nullable=True),
                    sa.Column('team', sa.Text(), nullable=True),
                    sa.Column('profession', sa.Text(), nullable=True),
                    sa.Column('score_red', sa.Integer(), nullable=True),
                    sa.Column('score_blue', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['map_id'], ['maps.id'])
                    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pvpmatches')
    op.drop_table('maps')
    ### end Alembic commands ###
