"""empty message

Revision ID: 5a477db4dfff
Revises: 364ed39a52b7
Create Date: 2015-11-07 17:24:58.705000

"""

# revision identifiers, used by Alembic.
revision = '5a477db4dfff'
down_revision = '364ed39a52b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TPtransactions',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('purchased', sa.DateTime(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TPtransactions')
    ### end Alembic commands ###
