"""empty message

Revision ID: 5cfcda404c4
Revises: None
Create Date: 2015-10-22 15:57:47.999000

"""

# revision identifiers, used by Alembic.
revision = '5cfcda404c4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('description', sa.String(length=128), nullable=True),
                    sa.Column('icon', sa.String(length=128), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('rarities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('icon', sa.String(length=128), nullable=True),
                    sa.Column('description', sa.String(length=128), nullable=True),
                    sa.Column('type_id', sa.Integer(), nullable=True),
                    sa.Column('rarity_id', sa.Integer(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('vendor_value', sa.Integer(), nullable=True),
                    sa.Column('default_skin', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['rarity_id'], ['rarities.id'], ),
                    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('walletdata',
                    sa.Column('dataId', sa.Integer(), nullable=False),
                    sa.Column('currencyId', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Integer(), nullable=True),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['currencyId'], ['currencies.id'], ),
                    sa.PrimaryKeyConstraint('dataId')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walletdata')
    op.drop_table('items')
    op.drop_table('types')
    op.drop_table('rarities')
    op.drop_table('currencies')
    ### end Alembic commands ###
